### ISSUE TITLE
GSC url property not found

### ISSUE THREAD

**Issue by MrZANO** [m3m3nto/giaa#1]
Ciao, ho provato a fare tutte le configurazioni che ci sono scritte nelle istruzioni, ma qualsiasi URL provo a pushare ottengo sempre 

GSC url property not found
 e sulla console (windoes)
Starting indexer service...
(node:9864) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#-findandmodify-

Hai qualche suggerimento da potermi dare?

**Comment by m3m3nto** [comment]
Ciao, hai agganciato anche la proprietà GSC nell'area di configurazione?
http://localhost:3000/config
GSC url property not found, indica che non viene trovata la property di Search Console associata al dominio della pagina che stai richiedendo.

Il  messaggio in console è relativo a mongoose, e non inficia l'attività dell'indexer.

**Comment by m3m3nto** [comment]
Dopo che hai scaricato il file del certificato in formato .json in Google API e associato l'account alla ownership di GSC, devi copiare il file nella directory config/cids.
Avvia Giaa come hai già fatto e vai nell'area di configurazione http://localhost:3000/config.
Associa il dominio di GSC al file json appena copiato:

[https://raw.githubusercontent.com/m3m3nto/giaa/master/public/img/giaa.png](url)

**Comment by MrZANO** [comment]
Grazie per l'aiuto,
ho fatto tutti i passi. 
Data l'autenticazione a GSC alla mail che mi ha generato il processo di gestione delle API e poi generato il json che ho inserito in cartella config/cids.
Niente non riesco a fare interrogazioni.

![Immagine](https://user-images.githubusercontent.com/14937718/58024442-79868e80-7b12-11e9-868a-9c0932ea60b5.png)

Hai qualche consiglio da darmi?

**Comment by MrZANO** [comment]
Ho paura che sia un problema di autenticaizione perchè dalle API non vedo passare nessuna richiesta.

Nella guida https://developers.google.com/search/apis/indexing-api/v3/prereqs non ho fatto la parte di "Ottenere un token di accesso" perchè immagino che il sistema richieda in automatico il token, ma non vedo passare richieste.

**Comment by MrZANO** [comment]
risolto, era un problema di match dei domini di search console. Il dominio che inserivo era senza / finale ed io inserivo lo slash in domain dell'applicativo. Adesso funziona correttamente!!!

**Comment by m3m3nto** [comment]
Bene!

**Comment by adrian-neadoo** [comment]
I'm gonna connect to that thread as I've got the same issue when running that locally 

trying to add the domain in multiple version with/without trailing slash at the end 
clear database and create it again but still got this "GSC url property not found"
have a look here please:
<img width="594" alt="Screenshot at Apr 20 13-51-01" src="https://user-images.githubusercontent.com/41481817/233357758-84d89845-ca07-412c-aa13-d9b725142a88.png">

**Comment by m3m3nto** [comment]
Hi @adrian-neadoo,
have you completed all the setup steps?
https://github.com/m3m3nto/giaa#giaa-basic-configuration

**Comment by adrian-neadoo** [comment]
@m3m3nto call looks like it's set correctly although I didn't touch the config/app.js file. 

I'm using the same JSON key in another tool and it works correctly 

I'm adding domain and checking that there are no whitespaces before/after but apparently I'm doing something wrong but don't have a clue what

**Comment by m3m3nto** [comment]
@adrian-neadoo There should be an exact match between the domain in GSC and the one in GIAA; i.e: if the domain in GSC is https://www.mysite.com/ the same domain should be added in GIAA.

![2023-04-21_11-22](https://user-images.githubusercontent.com/51357/233599788-601b6de9-ff4e-4d3f-bed0-6e484223e736.png)

Also verify that the Google Cloud service account has ownership permissions within the GSC.

![2023-04-21_11-21](https://user-images.githubusercontent.com/51357/233599726-f76bc281-cd5f-4449-9132-4eb1a84b5b8b.png)

**Comment by adrian-neadoo** [comment]
thanks for your time @m3m3nto appriciate it :)

yes so all looks good to me check out the 3 screenshot below 
1. the configuration in giaa - domain is in format https://mydomain.pl/ (with slash at the end) 
for a.json - but as earlier when trying to submit it returns "GSC url property not found" when trying to submit homepage in the same format 
2. GSC screenshot with users section the user is added as owner 
3. its a.json from cids - same email as in above GSC ;) checked via search to make sure there is no typo :D 

any idea what should I check more. 
I also try with different domain but same error. 

![1](https://user-images.githubusercontent.com/41481817/233607695-1d1f6be7-30c9-407e-9541-25e91f027ed5.jpg)

**Comment by m3m3nto** [comment]
Wich URL are you trying to send to the indexing api?
It contains a trailing slash?

**Comment by adrian-neadoo** [comment]
yes no matter if I use https://domain.pl domain.pl/ or subpage domain.pl/url

<img width="558" alt="Screenshot at Apr 21 14-10-30" src="https://user-images.githubusercontent.com/41481817/233632035-89e94cc0-3ce7-4518-a6c1-d6ea61346ee1.png">

**Comment by m3m3nto** [comment]
yes bu your requests points to http, but the registered domain is https. Isn't it?

**Comment by adrian-neadoo** [comment]
yeah you are right that in the previous I used http but with https it's stille the same 
<img width="563" alt="image" src="https://github.com/m3m3nto/giaa/assets/41481817/4bfba6eb-336d-4a29-9ddc-8a195b82c420">

**Comment by yordiverbeeck** [comment]
@adrian-ndo Have you every got this working? Running into the same issues

**Comment by adrian-ndo** [comment]
unfortunately no, I gave up tbh

**Comment by yordiverbeeck** [comment]
@adrian-ndo Alright thanks for the reply, after some more debugging I found the simple solution which was in the DB querying. Might fix it for you too if you were still hoping to get this working 😅
https://github.com/m3m3nto/giaa/pull/40
