### ISSUE TITLE
URL_DELETED su pagine in noindex

### ISSUE THREAD

**Issue by C0nrad92** [m3m3nto/giaa#9]
Ciao,
stavo provando a far funzionare GIAA, la funzione di update va benissimo, ma sono arrivato ad un punto cieco riguardo alle pagine in "noindex".

Secondo Google, per rimuovere una pagina dall'indice basta che "l'URL deve restituire un codice di stato 404 o 410 oppure la pagina deve contenere un meta tag -meta name="robots" content="noindex" /-".

Per fare delle prove ho inserito il tag noindex in alcune pagine, ma quando vado ad utilizzare GIAA mi da un errore.
Quindi sono andato a controllare il file "checker.js" nella cartella "modules", e ho notato che se l'url ha status 200, l'unico check che fa è controllare se la richiesta è di "update", altrimenti, se è una richiesta di "delete", da un messaggio di errore.

La mia domanda quindi è:
E' possibile utilizzare GIAA per togliere più pagine dall'indice di Google?
E se si, cosa starei facendo di sbagliato?

Ti ringrazio moltissimo!

Buona giornata!

**Comment by m3m3nto** [comment]
Ciao,
attualmente GIAA controlla preventivamente che la url sia stata eliminata e quindi risponda con un 404/410.
Nel tuo caso invece vuoi mantenere la pagina (200) ed eliminarla dall'indice, indicando solo un metatag robots.
Sicuramente è possibile intervenire in modo da ampliare il controllo preventivo e nel caso la pagina risponda 200 verificare che almeno esista il tag noindex.
Cerco di lavorare su questo comportamento appena possibile.
Grazie, della segnalazione!

**Comment by C0nrad92** [comment]
Ciao, ho fatto una piccola prova veloce andando a modificare il file checker.js 

![image](https://user-images.githubusercontent.com/72385123/95457716-94f57200-0971-11eb-8114-3f4cb49338a7.png)

Di sicuro non è il modo più giusto di farlo, e non sono nemmeno sicuro al 100% che funzioni (ho inserito 10 url e solo alcune sono state tolte dall'indice), ma è un inizio :D

**Comment by m3m3nto** [comment]
Così però lasci il notify su pending.
Comunque prima che le pagine vengano tolte dall'indice deve passare un po' di tempo.

**Comment by Tirex-pixel** [comment]
Ciao,
è possibile deindicizzare degli URL che sono in status code 200 e che non hanno il noindex?
(devo ancora trovare un modo per far aggiungere in meta robots noindex in bulk a numerose email.

Grazie

**Comment by m3m3nto** [comment]
@Tirex-pixel Ciao a te,
da quanto vedo dalla documentazione: 

https://developers.google.com/search/apis/indexing-api/v3/using-api#removing

Non è proprio possibile inviare una URL_REMOVED se la pagina non risponde con 404 o 410.
Mi spiace, grazie a te!
